name: Тестирование и развёртывание проекта


on:
  push:
    branches: [lower]


jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}
    services:
      postgresql_main:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Проверка репозитория на изменения
        uses: actions/checkout@v3


      - name: Установка python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.1


      - name: Установка зависимостей
        run: pip install -r  requirements.txt


      - name: Линтинг
        run: flake8 phones/ --exclude=phones/migrations/

      - name: Тесты
        run: python manage.py test
        env:
          SECRET_KEY: ${{env.SECRET_KEY}}
          ALLOWED_HOSTS: ${{env.ALLOWED_HOSTS}}
          DEBUG: ${{env.DEBUG}}
          DB_ENGINE: ${{env.DB_ENGINE}}
          DB_PORT: ${{env.DB_PORT}}
          DB_HOST: ${{env.DB_HOST}}
          DB_NAME: ${{env.DB_NAME}}
          DB_USER: ${{env.DB_USER}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}